# Generated by Django 3.2.5 on 2022-06-01 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('block', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('age', models.PositiveIntegerField()),
                ('religion', models.CharField(max_length=264)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='basic_app.villa')),
            ],
        ),
    ]
