# Generated by Django 3.2.5 on 2022-06-01 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='religion',
        ),
    ]
