# Generated by Django 3.2.5 on 2022-06-01 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_remove_owner_religion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
